### ISSUE TITLE
api?

### ISSUE THREAD

**Issue by karissa** [tlevine/openprism#2]
do you have an api?

**Comment by marks** [comment]
@karissa - I don't believe open prism has an API because it simply calls a bunch of other APIs including individual Socrata and CKAN sites. Socrata does have a new API where you can search all portals at once: it is at labs.socrata.com and has a front end at opendatanetwork.com. 

Hope this helps some!

**Comment by karissa** [comment]
@marks awesome thanks!

I've been working on this: http://github.com/karissa/dps, to aggregate these searchers. Implmented [figshare](http://github.com/karissa/figshare-search) and ckan, now working on this one.
